### ISSUE TITLE
support PITbv2

### ISSUE THREAD

**Issue by ejhoness** [FYSETC/FYSETC-PITB#8]
I'm sad about this, please show me a video of this working with klipper. A simple motor rotating connected to this. PITBv2. and the files used to run this motor.

**Comment by ejhoness** [comment]
Thanks for the update, but only temperature and end of stroke sensor. No motor and fans

[klippy_pitbv2.log](https://github.com/user-attachments/files/16910681/klippy_pitbv2.log)
![Captura de tela de 2024-09-06 13-32-23](https://github.com/user-attachments/assets/64b9b2ab-5a0c-47e5-af5c-2203f7cd95e9)
![Captura de tela de 2024-09-06 13-33-00](https://github.com/user-attachments/assets/aa9c0d36-a090-461c-a498-74bc455cbc40)

**Comment by ghost** [comment]
Got the spi bus working: https://github.com/Klipper3d/klipper/pull/6683

**Comment by ejhoness** [comment]
my pitbv2 is broken,
thanks, long life and prosperity.
